### ISSUE TITLE
Add Apache and PHP config into image

### ISSUE THREAD

**Issue by Parent5446** [sportarchive/docker-environments#4]
I think we will need to add the apache and php.ini file to the Docker config so we can tweak it at deploy time.

PHP needs to be updated for upload file size for example.
Apache to restrict the module loaded and the VirtualHost config for dev/qa/prod so it serves the proper domain.

Please change the upload_max_filesize and post_max_size in .htaccess file or php.ini.
I set these values in my local server php.ini file.
"post_max_size 40M"
"php_value upload_max_filesize 40M"

**Comment by koxon** [comment]
40M is certainly too little for uploading large files.
I think we should have something like 2 or 3 GB.

The problem is the POST request, we don't want 2 GB in the memory.
We have to send multiparts files as chunks.

**Comment by Parent5446** [comment]
Fixed in 74928814eea3631b22e3059f889929826b3ba0de. Forgot to reference issue in the commit msg.
